group_id = [123456, 1234567]

[deepseek]
  api_key  = ""
  base_url = "https://api.deepseek.com/"
  timeout  = 180000 # millisecond

[onebot]
  [onebot.ws_client]
    enabled = true
    url     = "ws://192.168.1.2:3001/"
    token   = ""

  [onebot.ws_server]
    enabled = false
    url     = "ws://0.0.0.0:3001/"
    token   = "admin"
