group_id = [1234, 5678]

[deepseek]
  api_key  = "<YOUR_API_KEY>"
  base_url = "https://api.deepseek.com/"
  timeout  = 180000 # millisecond

[onebot]
  [onebot.ws_client]
    enabled = true
    url     = "ws://127.0.0.1:3001/"
    token   = ""

  [onebot.ws_server]
    enabled = false
    url     = "ws://0.0.0.0:3001/"
    token   = ""

# generic options for renderer and browser
[chromedp]
  exec_path = "" # custom chromium kernel browser executable path
  proxy_url = "" # example http://127.0.0.1:8080, NOT add "/" at last

[renderer]
  enabled = true
  width   = 600
  height  = 200
  timeout = 15000 # millisecond

[emoticon]
  enabled = true
  rate    = 10 # 0-100%

[memory]
  enabled = true

# https://developers.google.com/custom-search/v1/reference/rest/v1/cse/list
[search_api]
  enabled   = true
  engine_id = "<YOUR_ENGINE_ID>"
  api_key   = "<YOUR_API_KEY>"
  proxy_url = ""
  timeout   = 15000 # millisecond

[browser]
  enabled = true
  timeout = 60000 # millisecond

[eval_go]
  enabled = true
  timeout = 300000 # millisecond
