group_id = [1234, 5678]

[deepseek]
  api_key  = "<YOUR_API_KEY>"
  base_url = "https://api.deepseek.com/"
  timeout  = 180000 # millisecond

[onebot]
  [onebot.ws_client]
    enabled = true
    url     = "ws://127.0.0.1:3001/"
    token   = ""

  [onebot.ws_server]
    enabled = false
    url     = "ws://0.0.0.0:3001/"
    token   = ""

[renderer]
  enabled   = true
  width     = 600
  height    = 200
  exec_path = "" # custom chromium kernel browser

[emoticon]
  rate = 10 # 0-100%

[fetch_url]
  enabled   = true
  timeout   = 60000 # millisecond
  proxy_url = ""
  exec_path = "" # custom chromium kernel browser

[eval_go]
  enabled = true
  timeout = 300000 # millisecond
